### ISSUE TITLE
hub: `scan_order`, `scans_count` and button targets in `waiving/result.html` may be incorrect

### ISSUE THREAD

**Issue by lzaoral** [openscanhub/openscanhub#110]
Schedule three errata scans:
1. First with `NEW_PACKAGE` as the base.
2. Immediately schedule the second one  with a proper package as the baseline instead and let it finish.
3. Finally, schedule the last one with a with `NEW_PACKAGE` as the base and let it finish as well.

* http://0.0.0.0:8000/waiving/1/ will show incorrect `scan_order` value:
![image](https://github.com/openscanhub/openscanhub/assets/48823770/5a9c990a-c9d2-4d66-9f9d-b23ebac0e169)

* http://0.0.0.0:8000/waiving/2/ will show incorrect `scan_order` value (or correct if you only care about successful scans) and correct `scan_count` (or incorrect if you only care about successful scans): <img width="1128" alt="image" src="https://github.com/openscanhub/openscanhub/assets/48823770/859fd75b-2bb8-4aa5-a4b7-e93fb5127c4e">
The `Next` button will go directly to http://0.0.0.0:8000/waiving/4/ (scan number 3).

* http://0.0.0.0:8000/waiving/3/ is a base scan and it does not show `Previous` and `Next` buttons: <img width="1125" alt="image" src="https://github.com/openscanhub/openscanhub/assets/48823770/fd9b995a-3fd7-4537-af5e-077e77887bf5">

* http://0.0.0.0:8000/waiving/4/ will show incorrect `scan_order` value (or correct if you only care about successful scans) and correct `scan_count` (or incorrect if you only care about successful scans): <img width="1125" alt="image" src="https://github.com/openscanhub/openscanhub/assets/48823770/725930b8-51f5-428a-b4e9-39a43fb92f7b">
The `Previous` button will go directly to http://0.0.0.0:8000/waiving/2/ (scan number 1).

--------

The feature is definitely broken but I'm not sure what the expected behaviour should be.  Do we want to list failed scans, do we want to list base scans, ...?

**Comment by lzaoral** [comment]
I suggest to modify the `scan_order` and `scan_count` variables to only consider scans scheduled by the Errata Tool.  Thus, base scans will not be taken into account because the `Previous` and `Next` buttons do not point to such scans anyway.

However, I'm not sure how to clearly show that a given scan is not included in that set and a plain `#` for the order is rather confusing.  @kdudka Do you have any ideas?

**Comment by kdudka** [comment]
Yes, it does not make any sense to show waiver page for a base scan.  It should be easy to identify base scans because they have `ERRATA_BASE` in `Scan Type`.  If I remember correctly, target scans can be reused as baselines for subsequent differential scans but not vice versa (scans triggered as baseline are never reused as target scans).
