### ISSUE TITLE
hub: add some checker groups to initial fixtures 

### ISSUE THREAD

**Issue by lzaoral** [openscanhub/openscanhub#111]
We should ship initial fixtures with some basic checker groups added, if possible.  Otherwise, all results will be marked as `Unsorted`: ![](https://user-images.githubusercontent.com/48823770/263649388-725930b8-51f5-428a-b4e9-39a43fb92f7b.png)

**Comment by kdudka** [comment]
The legacy checker groups we use internally are specific to Coverity.  The most interesting checker groups are the ones that were added recently for the open-source scanners and those should be upstreamed:

- `Compiler Warnings` for `COMPILER_WARNING`
- `Cppcheck Warnings` for `CPPCHECK_WARNING`
- `Shell` for `SHELLCHECK_WARNING`
- `GCC Analyzer` for `GCC_ANALYZER_WARNING`
- `Clang` for `CLANG_WARNING`
- `Hard-coded Secrets` for `GITLEAKS_WARNING`
