### ISSUE TITLE
ci: drop `codecov` from the default CI jobs

### ISSUE THREAD

**Issue by kdudka** [openscanhub/openscanhub#136]
It is really annoying if all upstream commits have red CI because of `codecov`.  Let's remove `codecov` from the CI until we find out how to integrate it in a more useful way.

**Comment by lzaoral** [comment]
What about changing the configuration instead? https://docs.codecov.com/docs/codecovyml-reference#coveragerange

**Comment by kdudka** [comment]
I am not very passionate about it to be honest.  Please show me some pull requests where the `codecov` CI job helped you.

**Comment by lzaoral** [comment]
Yes, for example https://github.com/openscanhub/openscanhub/pull/79#pullrequestreview-1551886372 and https://github.com/openscanhub/openscanhub/pull/97#issuecomment-1683903894.

**Comment by siteshwar** [comment]
> What about changing the configuration instead? https://docs.codecov.com/docs/codecovyml-reference#coveragerange

What would be an acceptable coverage range to keep CI green? Shall it be between 45 to 100?

**Comment by kdudka** [comment]
I still think that `codecov` should be non-voting.  Measuring test coverage is useful.  Making CI red based on its results is practically never useful in my view.

**Comment by siteshwar** [comment]
> I still think that `codecov` should be non-voting. Measuring test coverage is useful. Making CI red based on its results is practically never useful in my view.

If the coverage drops to 0%, that means something is broken either in the CI or related code. I still believe it would be useful to have a minimal threshold for such cases.

**Comment by kdudka** [comment]
Fair enough.  Let's set the threshold to something that will keep CI green under normal circumstances.

**Comment by siteshwar** [comment]
There are 2 separate causes of failure:

- Tests are flaky and overall coverage is in the range between 50 to 60 percent.
- There are 2 separate jobs that measure test coverage, unit tests and integration tests. Usually unit tests finish first and they have coverage around 40%, so CI is kept temporarily red until both of them have finished.

We should try setting coverage target to 40% and see how it goes.
