### ISSUE TITLE
ci: What shall we do with `scripts/cli_sanity_test.sh`?

### ISSUE THREAD

**Issue by lzaoral** [openscanhub/openscanhub#150]
This script seems to be unfinished and is not executed in the CI.

**Comment by lzaoral** [comment]
@kdudka Do you think that it is sensible to finish it or that removal is more feasible?

**Comment by kdudka** [comment]
The script seems outdated (function names start with `cov-` prefixes, etc.), so I would just drop it.

**Comment by kdudka** [comment]
I can see the script is being removed by #188.
