### ISSUE TITLE
docs: what shall we use for OpenScanHub documentation?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub#154]
We currently have a very limited documentation of OpenScanHub in the git repository.  We should choose a platform for documentation to make it easier for the users to learn and use OpenScanHub.

**Comment by lzaoral** [comment]
I suggest to use the OSH website for that purpose.

**Comment by siteshwar** [comment]
@kdudka suggested to use [Github wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) as it can be easily maintained through Git.
