### ISSUE TITLE
client: change default hub url to `openscanhub.fedoraproject.org`

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub#195]
We plan to have a deployment for [Fedora](https://pagure.io/fedora-infrastructure/issue/11632) on `openscanhub.fedoraproject.org`. This issue track changing default hub url in [client](https://github.com/openscanhub/openscanhub/blob/69a30647074c14e9bff4fcfd422dd1e83394e2e6/osh/client/client.conf#L5) to `openscanhub.fedoraproject.org` and doing a package release for Fedora.

EDIT: Use `openscanhub.fedoraproject.org` instead of `openscanhub.fedorainfracloud.org`.

**Comment by lzaoral** [comment]
Great idea!  I've filled https://issues.redhat.com/browse/OSH-444 so that this change won't the internal deployment of OSH.

**Comment by lzaoral** [comment]
Note that we should also remove all references to `brew` in the upstream client configurations (and perhaps replace that with the `stream` Koji profile but that also requires #127 to be resolved first).

**Comment by kdudka** [comment]
We have an interim solution in-place for the internal deployment.  Please feel free to change `HUB_URL` and `KOJI_PROFILES` in https://github.com/openscanhub/openscanhub/blob/main/osh/client/client.conf

**Comment by siteshwar** [comment]
> We have an interim solution in-place for the internal deployment. Please feel free to change HUB_URL and KOJI_PROFILES in https://github.com/openscanhub/openscanhub/blob/main/osh/client/client.conf

The production deployment does not exist for Fedora and I still need to get feedback from the Fedora community. We should probably do it when production is in place.

**Comment by siteshwar** [comment]
@kdudka Shall we move [version number](https://github.com/openscanhub/openscanhub/blob/6991f8836f297a8d862b12cf5e8b85e3c920d152/setup.py#L14) to `1.0.0` on this change?

**Comment by kdudka** [comment]
@siteshwar Yes, it sounds like a good idea.  This is also perfectly aligned with the migration off my personal COPR namespace for the internal deployment: `osh-cli-1.0.0` will be the first release available on the new location only.

**Comment by siteshwar** [comment]
Review Request: osh - Static and Dynamic Analysis as a Service - https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2275304

**Comment by siteshwar** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2024-a151870abf - rawhide
https://bodhi.fedoraproject.org/updates/FEDORA-2024-c5a16638c9 - f40
https://bodhi.fedoraproject.org/updates/FEDORA-2024-04aa4e4ca8 - f39
