### ISSUE TITLE
Shall we remove `Hostname` field from e-mail notifications?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub#255]
[This field](https://github.com/openscanhub/openscanhub/blob/6991f8836f297a8d862b12cf5e8b85e3c920d152/osh/hub/scan/notify.py#L104) translates to name of the container in the OpenShift deployment. For example, `fedora-osh-hub-5b76575868-2r48q`. I consider this field to be unnecessary for the user, as they have a url to the task in the e-mail notification. I propose this field should be removed from the notifications.

**Comment by kdudka** [comment]
@siteshwar Yes, the `Hostname: ` line in the body of e-mail notifications is redundant.  Let's remove it.
