### ISSUE TITLE
Add file extensions to download links

### ISSUE THREAD

**Issue by Venefilyn** [openscanhub/openscanhub#303]
With the log download links at the bottom of a task it currently shows as `added.js?format=raw` which doesn't indicate what the format is. Could it be possible to show the extensions at the end of the  URL? I.e. just something like `added` for the HTML view and `added.json` for the download link.

**Comment by kdudka** [comment]
@Venefilyn Thanks for feedback!  These URLs are enforced by the underlying `kobo` framework.  I have proposed to change this: https://github.com/release-engineering/kobo/pull/266

Let's see what `kobo` upstream thinks about it.
