### ISSUE TITLE
Shall we add a development workflow check for macOS in GitHub Actions CI?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub#68]
As we have started working towards stabilizing development workflow on macOS, we should consider adding a check for it on GitHub Actions CI.

**Comment by lzaoral** [comment]
This is blocked on #67 and #74.

**Comment by lzaoral** [comment]
The macOS machines provided by GitHub are practically unusable for our testing. Therefore, I suggest to just test changes which may affect this platform manually.
