### ISSUE TITLE
Shall we use resalloc to dynamically provision workers?

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub#82]
I am opening this issue after discussing dynamic provisioning of workers with @lzaoral and @praiskup.

resalloc is a resource manager for resources like virtual machines, containers etc. It is used inside Copr infrastrucutre to manage builders (workers). It currently support AWS, OpenStack, IBM cloud, kubernetes etc. and is extensible to other infrastrucutres. We can possibly use resalloc to dynamically allocate and manage workers in OpenScanHub deployments. This issue tracks if we should have a hard dependency on resalloc. If not, how resalloc could be used with OpenScanHub for dynamic provisioning of workers.

Project page:
- https://github.com/praiskup/resalloc

Fedora Copr configuration:
- https://pagure.io/fedora-infra/ansible/blob/main/f/roles/copr/backend/templates/resalloc/pools.yaml
- https://pagure.io/fedora-infra/ansible/blob/main/f/roles/copr/backend/templates/resalloc/server.yaml

The current "state" of the systems (overview page):
- https://copr-be.cloud.fedoraproject.org/resalloc/

Available in Fedora and Fedora EPEL:
- https://src.fedoraproject.org/rpms/resalloc/branches

Helper scripts for starting VMs:
- https://src.fedoraproject.org/rpms/resalloc-aws
- https://src.fedoraproject.org/rpms/resalloc-openstack

Example: [vm_alloc.py](https://github.com/fedora-copr/copr/blob/7442ec4303f2e0ba2e31a6555c4da34b96de0ee1/backend/copr_backend/vm_alloc.py)
Internal GitLab issue: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/95

**Comment by praiskup** [comment]
> I am opening this issue after discussing dynamic provisioning of workers with @lzaoral and @praiskup.

Thank you for the issue!  Just a few additions:

> It is used inside Copr infrastrucutre to manage builders (workers).

Yes, exactly - the "Builder" and "Worker" are a bit confusing terms when we talk about OpenScanHub and Copr. Copr isn't using the Kobo framework; in the [Copr architecture](https://docs.pagure.org/copr.copr/developer_documentation/architecture.html) we have basically just one "Worker" (named Backend), and that "Worker" controls all the (hundreds of) tasks in parallel and delegates the heavy work (Mock processes) to Builders over SSH.

> Example: [vm_alloc.py](https://github.com/fedora-copr/copr/blob/7442ec4303f2e0ba2e31a6555c4da34b96de0ee1/backend/copr_backend/vm_alloc.py)

If this needs to be generalized into a library for better reuse, let us know.

**Comment by siteshwar** [comment]
I discussed this issue with @kdudka and we agreed to introduce an optional dependency on `resalloc` in `hub` component.

**Comment by siteshwar** [comment]
This issue is still working in progress.  @praiskup is prototyping a daemon that should fit OpenScanHub's workflow to dynamically spin up workers (https://github.com/praiskup/resalloc/pull/125).

**Comment by siteshwar** [comment]
This has been fixed through https://github.com/openscanhub/openscanhub/pull/234
